"""create search_sessions table

Revision ID: 6d221b598335
Revises: 
Create Date: 2026-02-26 11:20:48.034692
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d221b598335'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_sessions',
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('query_type', sa.String(length=32), nullable=False),
    sa.Column('search_mode', sa.String(length=32), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('pico', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_identified', sa.Integer(), nullable=False),
    sa.Column('total_after_dedup', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('sources_completed', sa.JSON(), nullable=False),
    sa.Column('sources_failed', sa.JSON(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_sessions_created_at_desc', 'search_sessions', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_search_sessions_created_at_desc', table_name='search_sessions')
    op.drop_table('search_sessions')
    # ### end Alembic commands ###
